# Generated by Django 5.2 on 2025-05-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pakets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('image', models.ImageField(upload_to='media/')),
            ],
            options={
                'verbose_name': 'пакет',
                'verbose_name_plural': 'пакеты',
            },
        ),
    ]
